import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Home/Navbar";
import {  Inter } from 'next/font/google'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ["400", "700"],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <div className={`w-screen h-screen overflow-y-auto scrollbar-hide ${inter.className}`}>
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  );
}
